name: Clear Cache
on: workflow_dispatch
jobs:
  clear:
    runs-on: ubuntu-latest
    if: github.repository == 'knijam/card-website'

    steps:
      - name: Use gh api
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh api -X DELETE /repos/${{ github.repository }}/actions/caches