name: Clear Cache
on: workflow_dispatch
jobs:
  clear:
    runs-on: ubuntu-latest
    if: github.repository == 'knijam/card-website'

    steps:
      - name: Use gh api
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh cache delete --all --repo ${{ github.repository }}